import 'package:cloud_firestore/cloud_firestore.dart';

/// Represents a single DSA problem generated by the AI Roadmap Generator.
/// Saved to Firestore under users/{uid}/data/dsa_problems/items/ after the
/// user confirms and taps "Save to DSA Tracker".
class RoadmapProblem {
  String topic;
  String title;
  String difficulty; // "Easy", "Medium", or "Hard"
  String whyImportant; // One-line explanation from the AI
  bool isSolved;

  RoadmapProblem({
    required this.topic,
    required this.title,
    required this.difficulty,
    required this.whyImportant,
    this.isSolved = false,
  });

  /// Creates a [RoadmapProblem] from a raw JSON map returned by the AI.
  factory RoadmapProblem.fromMap(Map<String, dynamic> map) {
    return RoadmapProblem(
      topic: (map['topic'] as String? ?? '').trim(),
      title: (map['title'] as String? ?? '').trim(),
      difficulty: (map['difficulty'] as String? ?? 'Medium').trim(),
      whyImportant: (map['whyImportant'] as String? ?? '').trim(),
      isSolved: false,
    );
  }

  /// Serializes the problem to a Firestore-compatible map.
  /// Uses the same schema as [DSAProblem] so it integrates seamlessly with
  /// the existing DSA Tracker screen.
  Map<String, dynamic> toMap() {
    return {
      'topic': topic,
      'title': title,
      'difficulty': difficulty,
      'isSolved': isSolved,
      'createdAt': Timestamp.fromDate(DateTime.now()),
      // Extra field for traceability — tells the DSA Tracker this came from AI
      'source': 'roadmap',
    };
  }
}
